apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
spec:
  selector:
    matchLabels:
      app: api-gateway
  replicas: 1
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
      - name: api-gateway
        image: berly01/diary-api-gateway:latest
        ports:
        - containerPort: 5000
        env:
        - name: SECRET_KEY
          value: tu_clave_secreta_super_segura_123
        - name: LOGIN_SERVICE
          value: http://login-service:5001
        - name: ENTRY_SERVICE
          value: http://entry-service:5002
        - name: SEARCH_SERVICE
          value: http://search-service:5003
---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway
spec:
  type: NodePort
  selector:
    app: api-gateway
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30080
