apiVersion: apps/v1
kind: Deployment
metadata:
  name: search-service
spec:
  selector:
    matchLabels:
      app: search-service
  replicas: 1
  template:
    metadata:
      labels:
        app: search-service
    spec:
      containers:
      - name: search-service
        image: berly01/diary-search-service:latest
        ports:
        - containerPort: 5003
        env:
        - name: DB_HOST
          value: mysql
        - name: DB_USER
          value: root
        - name: DB_PASSWORD
          value: rootpassword
        - name: DB_NAME
          value: diary_db
        - name: SECRET_KEY
          value: tu_clave_secreta_super_segura_123
---
apiVersion: v1
kind: Service
metadata:
  name: search-service
spec:
  type: ClusterIP
  selector:
    app: search-service
  ports:
    - port: 5003
      targetPort: 5003
